# Generated by Django 4.2.4 on 2023-09-28 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('identificator', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('denomination', models.CharField(max_length=50, unique=True, verbose_name='Country')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Code')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
                'ordering': ['identificator'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('identificator', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('denomination', models.CharField(max_length=25, unique=True, verbose_name='Gender')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
                'db_table': 'gender',
                'ordering': ['identificator'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('identificator', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('email', models.EmailField(max_length=350, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('firstLastname', models.CharField(max_length=25, verbose_name='First Lastname')),
                ('secondLastname', models.CharField(max_length=25, null=True, verbose_name='Second Lastname')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(130)], verbose_name='Age In Years')),
                ('password', models.CharField(max_length=150, verbose_name='Encrypted Password')),
                ('agreedPolicies', models.BooleanField(default=True, verbose_name='Agreed Policies')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='Registered')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SEL4C.country', verbose_name='Country')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SEL4C.gender', verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['identificator'],
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('identificator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SEL4C.user', unique=True, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'db_table': 'administrator',
                'ordering': ['identificator'],
            },
        ),
    ]
