# Generated by Django 4.1.7 on 2023-10-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SEL4C.group', verbose_name='Grupo'),
        ),
    ]
