# Generated by Django 4.1.7 on 2023-10-19 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablestudies',
            options={'ordering': ['institution'], 'verbose_name': 'Estudio disponible', 'verbose_name_plural': 'Esudios disponibles'},
        ),
        migrations.AlterField(
            model_name='availablestudies',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEL4C.degree', verbose_name='Título académico'),
        ),
        migrations.AlterField(
            model_name='availablestudies',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEL4C.discipline', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='availablestudies',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEL4C.institution', verbose_name='Institución'),
        ),
    ]
