# Generated by Django 4.1.7 on 2023-10-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
