# Generated by Django 4.1.7 on 2023-10-05 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
