# Generated by Django 4.1.7 on 2023-10-20 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0002_alter_availablestudies_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablestudies',
            options={'ordering': ['institution'], 'verbose_name': 'Estudios', 'verbose_name_plural': 'Esudios'},
        ),
    ]
