# Generated by Django 4.1.7 on 2023-10-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
