# Generated by Django 4.2.4 on 2023-09-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0002_academicdegree_academicdegreeoffer_group_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academicDisciplines',
            field=models.ManyToManyField(to='SEL4C.academicdiscipline'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='identificator',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SEL4C.user', verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='identificator',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SEL4C.user', verbose_name='ID'),
        ),
    ]
