# Generated by Django 4.2.4 on 2023-09-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0004_competence_diagnosisquestion_implementationprocess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingreagent',
            name='questions',
            field=models.TextField(null=True, verbose_name='Questions'),
        ),
    ]
