# Generated by Django 4.2.4 on 2023-09-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0005_trainingreagent_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SEL4C.gender', verbose_name='Gender'),
        ),
    ]
