# Generated by Django 4.2.4 on 2023-09-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdiscipline',
            name='denomination',
            field=models.CharField(max_length=25, verbose_name='Academic Discipline'),
        ),
    ]
