# Generated by Django 4.2.4 on 2023-09-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0007_alter_academicdiscipline_denomination'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicdegreeoffer',
            unique_together=set(),
        ),
    ]
